# Setup
title: Blog
tagline: The Shini
url: https://d-shinigami.github.io
paginate: 1
baseurl: ""
permalink: pretty

pages_list:
  О блоге: '/about'
  Архив записей: '/archive'
#  Лента: '/atom.xml'


# Gems
plugins_dir:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-paginate

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed


# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Shini
  url: https://d-shinigami.github.io
  email: d.sh.gami@gmail.com

# Custom vars
version: 3.0.0

theme: jekyll-theme-slate
